spring.application.name=MindCheck
logging.level.org.springframework.web=DEBUG
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
jwt.token-validity-seconds=86400
jwt.base64-secret=eGrKeVE3WhUffvOEQZiIsOC4r4qS6tszSJhnlfRwvJo4F0WKfjC3QQNsuJZ95gVUHOKslhSsD5L9v3VxzxJO12